sudo: false
language: python

install:
  - pip install tox codecov pytest-cov

script:
  - tox

matrix:
  include:
    - python: "3.6"
      env: TOXENV='py36'
    - python: "3.5"
      env: TOXENV='py35'
    - python: "3.4"
      env: TOXENV='py34'
    - python: "3.3"
      env: TOXENV='py33'
    - python: "pypy3"
      env: TOXENV='pypy3'
    - python: "3.6"
      env: TOXENV='flake8'

script:
  - py.test --cov=ogn_lib tests

after_success:
  - codecov
