sudo: false
language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "pypy3"

install:
  - pip install tox 

script:
  - tox

env:
  - TOXENV='py36'
  - TOXENV='py35'
  - TOXENV='py34'
  - TOXENV='py33'
  - TOXENV='pypy3'
